truenas:
    api:
        host: "https://192.168.X.X"
        path: "/api/v2.0"
        key: "1-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

shares:
    - "tank/dataset-to-share-recursively-1"
    - "tank/other-dataset/with/deeper/nesting"
    - "tank/readonly-dataset"
    - "tank/dataset-with-different-user"

share_options:
    default:
        networks: []
        hosts:
            - "192.168.Y.Y"
        ro: false
        maproot_user: host-user-for-shares
        maproot_group: host-user-for-shares
        mapall_user: ~
        mapall_group: ~

    custom:
        "tank/readonly-dataset":
            ro: true
        "tank/dataset-with-different-user":
            maproot_user: other-user